AMP_VERBOSE: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  NUM_WORKERS: 0
  SIZE_DIVISIBILITY: 32
  BATCH_SIZE: 4
DATASETS:
  ROOT_DIR: /media/hdd/leetop/data/waymo/
  TEST: []
  TRAIN: track_data_plus_filtered.csv
  # TRAIN: filtered_valid_dataset.csv
  # TRAIN: GODTrain211111_mini_plus.csv
  # - MOT17
DTYPE: float32
INFERENCE:
  CLIP_LEN: 1
  USE_GIVEN_DETECTIONS: true
INPUT:
  AMODAL: true
  BRIGHTNESS: 0.1
  COMPRESSION_LIMIT: 50
  CONTRAST: 0.1
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  HUE: 0.1
  MAX_SIZE_TEST: 1500
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN:
  - 640
  - 720
  - 800
  - 880
  - 960
  MOTION_BLUR_PROB: 1.0
  MOTION_LIMIT: 0.1
  PIXEL_MEAN:
  - 0.485
  - 0.456
  - 0.406
  PIXEL_STD:
  - 0.229
  - 0.224
  - 0.225
  SATURATION: 0.1
  TO_BGR255: false
  VERTICAL_FLIP_PROB_TRAIN: 0.0
MODEL:
  BACKBONE:
    CONV_BODY: DLA-34-FPN
    FREEZE_CONV_BODY_AT: 2
  BOX_ON: true
  CLS_AGNOSTIC_BBOX_REG: false
  DEVICE: cuda
  DLA:
    BACKBONE_OUT_CHANNELS: 224
    DLA_STAGE2_OUT_CHANNELS: 64
    DLA_STAGE3_OUT_CHANNELS: 128
    DLA_STAGE4_OUT_CHANNELS: 256
    DLA_STAGE5_OUT_CHANNELS: 512
    STAGE_WITH_DCN:
    - false
    - false
    - false
    - false
    - false
    - false
  FBNET:
    ARCH: default
    ARCH_DEF: ''
    BN_TYPE: bn
    DET_HEAD_BLOCKS: []
    DET_HEAD_LAST_SCALE: 1.0
    DET_HEAD_STRIDE: 0
    DW_CONV_SKIP_BN: true
    DW_CONV_SKIP_RELU: true
    KPTS_HEAD_BLOCKS: []
    KPTS_HEAD_LAST_SCALE: 0.0
    KPTS_HEAD_STRIDE: 0
    MASK_HEAD_BLOCKS: []
    MASK_HEAD_LAST_SCALE: 0.0
    MASK_HEAD_STRIDE: 0
    RPN_BN_TYPE: ''
    RPN_HEAD_BLOCKS: 0
    SCALE_FACTOR: 1.0
    WIDTH_DIVISOR: 1
  FPN:
    USE_GN: false
    USE_RELU: false
  GROUP_NORM:
    DIM_PER_GP: -1
    EPSILON: 1.0e-05
    NUM_GROUPS: 32
  KEYPOINT_ON: false
  MASK_ON: false
  META_ARCHITECTURE: GeneralizedRCNN
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    DEFORMABLE_GROUPS: 1
    NUM_GROUPS: 1
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STAGE_WITH_DCN:
    - false
    - false
    - false
    - false
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: true
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    WIDTH_PER_GROUP: 64
    WITH_MODULATED_DCN: false
  RETINANET:
    ANCHOR_SIZES:
    - 32
    - 64
    - 128
    - 256
    - 512
    ANCHOR_STRIDES:
    - 8
    - 16
    - 32
    - 64
    - 128
    ASPECT_RATIOS: &id002
    - 0.5
    - 1.0
    - 2.0
    BBOX_REG_BETA: 0.11
    BBOX_REG_WEIGHT: 4.0
    BG_IOU_THRESHOLD: 0.4
    FG_IOU_THRESHOLD: 0.5
    INFERENCE_TH: 0.05
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    NMS_TH: 0.4
    NUM_CLASSES: 81
    NUM_CONVS: 4
    OCTAVE: 2.0
    PRE_NMS_TOP_N: 1000
    PRIOR_PROB: 0.01
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: 0
    USE_C5: true
  RETINANET_ON: false
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 4
    NUM_STACKED_CONVS: 4
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: &id003
    - 0.25
    - 0.125
    - 0.0625
    - 0.03125
    PREDICTOR: FPNPredictor
    USE_GN: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_WEIGHTS:
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    BG_IOU_THRESHOLD: 0.5
    DETECTIONS_PER_IMG: 100
    FG_IOU_THRESHOLD: 0.5
    NMS: 0.5
    POSITIVE_FRACTION: 0.25
    SCORE_THRESH: 0.3
    USE_FPN: true
  ROI_KEYPOINT_HEAD:
    CONV_LAYERS:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    FEATURE_EXTRACTOR: KeypointRCNNFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: &id001
    - 0.0625
    PREDICTOR: KeypointRCNNPredictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
  ROI_MASK_HEAD:
    CONV_LAYERS:
    - 256
    - 256
    - 256
    - 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: *id001
    POSTPROCESS_MASKS: false
    POSTPROCESS_MASKS_THRESHOLD: 0.5
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
    USE_GN: false
  RPN:
    ANCHOR_SIZES:
    - 32
    - 64
    - 128
    - 256
    - 512
    ANCHOR_STRIDE:
    - 4
    - 8
    - 16
    - 32
    - 64
    ASPECT_RATIOS: *id002
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_PER_BATCH: true
    FPN_POST_NMS_TOP_N_TEST: 300
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 2000
    RPN_HEAD: SingleConvRPNHead
    STRADDLE_THRESH: 0
    USE_FPN: true
  RPN_ONLY: false
  TRACK_HEAD:
    BG_IOU_THRESHOLD: 0.35
    EMM:
      CLS_POS_REGION: 0.8
      COSINE_WINDOW_WEIGHT: 0.4
      HN_RATIO: 0.25
      POS_RATIO: 0.4
      TRACK_LOSS_WEIGHT: 1.0
      USE_CENTERNESS: true
    FG_IOU_THRESHOLD: 0.65
    IMM:
      FC_HEAD_DIM: 256
      FC_HEAD_DIM_MULTIPLIER: 2
    MAX_DORMANT_FRAMES: 10
    MINIMUM_SREACH_REGION: 0
    MODEL: EMM
    PAD_PIXELS: 512
    POOLER_RESOLUTION: 15
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: *id003
    PROPOSAL_PER_IMAGE: 256
    RESUME_TRACK_THRESH: 0.4
    SEARCH_REGION: 2.0
    START_TRACK_THRESH: 0.6
    TRACKTOR: false
    TRACK_THRESH: 0.4
  TRACK_ON: true
  WEIGHT: ''
OUTPUT_DIR: .
PATHS_CATALOG: /media/hdd/leetop/projects/maskrcnn-benchmark/maskrcnn_benchmark/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 5000
  GAMMA: 0.1
  IMS_PER_BATCH: 16
  MAX_ITER: 25000
  MOMENTUM: 0.9
  STEPS:
  - 20000
  - 50000
  TEST_PERIOD: 0
  VIDEO_CLIPS_PER_BATCH: 2
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
TEST:
  BBOX_AUG:
    ENABLED: false
    H_FLIP: false
    MAX_SIZE: 4000
    SCALES: []
    SCALE_H_FLIP: false
  DETECTIONS_PER_IMG: 100
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 8
VIDEO:
  RANDOM_FRAMES_PER_CLIP: 2
  TEMPORAL_SAMPLING: 1000
  TEMPORAL_WINDOW: 1000
